version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    container_name: test-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests
    env_file:
      - .env.test
